### ISSUE TITLE
Convert edx-org action references to openedx-org

### ISSUE THREAD

**Issue by nedbat** [edx/.github#28]
Sarina recently went through all of the repos in the openedx org looking for "github.com/edx" and changing them where needed to "github.com/openedx".  This included the workflow references to "github.com/edx/.github" so they referred to "github.com/openedx/.github" instead.

We should also do this for repos in the edx GitHub organization. Many of them are referencing workflows in "github.com/edx/.github" when they should be using "github.com/openedx/.github".

**Comment by aht007** [comment]
The below PRs need attention from owning teams. I have already pinged the teams on their respective PRs
https://github.com/edx/braze-client/pull/12
https://github.com/edx/edx-prefectutils/pull/76
https://github.com/edx/dbt-schema-builder/pull/75
https://github.com/edx/financial-assistance/pull/44

**Comment by iamsobanjaved** [comment]
Re-shared the PRs with owning teams as we don't have merge access there.

**Comment by jristau1984** [comment]
Pinged the data team to review these PRs: https://twou.slack.com/archives/C5G3S8SNA/p1718245078770989

**Comment by iamsobanjaved** [comment]
All PRs now merged, so closing this finally.
